/*
 * ButtonPanel.java
 *
 * Created on August 11, 2006, 11:18 PM
 */

package slots.gui;

import slots.logic.ReelEventListener;

/**
 *
 * @author  Mark
 */
public class ButtonPanel extends javax.swing.JPanel implements ReelEventListener {
    private ReelPanel reelPanel;
    private final static String GAME_OVER = "Game Over";
    private final static String SPINNING = "Spinning...";
    
    /** Creates new form ButtonPanel */
    public ButtonPanel( ReelPanel reelPanel) {
        this.reelPanel = reelPanel;
        initComponents();
        ReelScrollPanel lastReel = this.reelPanel.getLastReel();
        lastReel.addReelEventListener(this);
        statusLabel.setText(GAME_OVER);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        spinButton = new javax.swing.JButton();
        LinesBetSelectButons = new javax.swing.JPanel();
        OneLineSelectButton = new javax.swing.JButton();
        ThreeLineSelectButon = new javax.swing.JButton();
        FiveLineSelectButton = new javax.swing.JButton();
        NineLineSelectButton = new javax.swing.JButton();
        FifteenLineSelectButton = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        statusLabel.setText("Game Over");
        jPanel1.add(statusLabel);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        spinButton.setText("Spin");
        spinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spinButtonActionPerformed(evt);
            }
        });

        add(spinButton, java.awt.BorderLayout.EAST);

        LinesBetSelectButons.setLayout(new java.awt.GridLayout(2, 5, 5, 10));

        OneLineSelectButton.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        OneLineSelectButton.setText("1 Line");
        LinesBetSelectButons.add(OneLineSelectButton);

        ThreeLineSelectButon.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        ThreeLineSelectButon.setText("3 Lines");
        LinesBetSelectButons.add(ThreeLineSelectButon);

        FiveLineSelectButton.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        FiveLineSelectButton.setText("5 Lines");
        LinesBetSelectButons.add(FiveLineSelectButton);

        NineLineSelectButton.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        NineLineSelectButton.setText("9 Lines");
        LinesBetSelectButons.add(NineLineSelectButton);

        FifteenLineSelectButton.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        FifteenLineSelectButton.setText("15 Lines");
        LinesBetSelectButons.add(FifteenLineSelectButton);

        jButton8.setText("1");
        LinesBetSelectButons.add(jButton8);

        jButton10.setText("2");
        LinesBetSelectButons.add(jButton10);

        jButton5.setText("3");
        LinesBetSelectButons.add(jButton5);

        jButton6.setText("4");
        LinesBetSelectButons.add(jButton6);

        jButton4.setText("5");
        LinesBetSelectButons.add(jButton4);

        add(LinesBetSelectButons, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

    private void spinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spinButtonActionPerformed
// TODO add your handling code here:
        reelPanel.setSpin( true );
        spinButton.setEnabled(false);
        statusLabel.setText(SPINNING);
        reelPanel.repaint();
    }//GEN-LAST:event_spinButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FifteenLineSelectButton;
    private javax.swing.JButton FiveLineSelectButton;
    private javax.swing.JPanel LinesBetSelectButons;
    private javax.swing.JButton NineLineSelectButton;
    private javax.swing.JButton OneLineSelectButton;
    private javax.swing.JButton ThreeLineSelectButon;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JButton spinButton;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables

    /** Listens to the last reel so we can do payout
     *  and button managmement.
     */
    public void observedReelStopped() {
        statusLabel.setText(GAME_OVER);
        spinButton.setEnabled(true);
        reelPanel.repaint();
    }

    public void reelValueChanged(int value) {
    }

}
